#!/bin/bash
#SBATCH -A CS4380_5351_7332 # account name
#SBATCH -J p6_collatz4      # job name
#SBATCH -o p6_collatz4.%j   # name of the output and error file
#SBATCH -N 4                # total number of nodes requested
#SBATCH -n 4                # total number of tasks requested
#SBATCH -p gpu              # queue name
#SBATCH -t 00:03:00         # expected maximum runtime (hh:mm:ss)

date

export OMP_NUM_THREADS=20

ibrun tacc_affinity ./collatz_hyb 1699416735 100

date
